name: Monthly Build & Release

on:
  schedule:
    - cron: '10 21 1 * *'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python (64-bit)
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      
      - name: Unzip ffmpeg
        run: 7z x ffmpeg.7z -y

      - name: Install dependencies (test + build)
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings || exit 1

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile  --hide-console=hide-early --add-binary "ffmpeg.exe;."   --add-data "loading.gif;." --add-data "overlay.gif;." --icon=favicon.ico  youtube_to_mp3.py

      - name: Prepare release tag
        id: prepare_tag
        run: |
          echo "TAG=v$(date +%Y-%m-%d)" >> $GITHUB_ENV
          echo "RELEASE_NAME=Monthly Release $(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Determine HEAD commit
        id: get_commit
        run: echo "COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG }}
          commit: ${{ env.COMMIT }}       # <--- The HEAD commit of main
          name: ${{ env.RELEASE_NAME }}
          body: "Automated monthly release."
          draft: false
          prerelease: false
          artifacts: "dist/youtube_to_mp3.exe"
