name: Monthly Build and Release II
on:
  schedule:
    # Runs on the first day of each month at midnight UTC
    - cron: '00 17 2 * *'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up environment (optional for Python/Node.js/other projects)
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.15'
          architecture: 'x64'
      - name: Unzip ffmpeg
        run: 7z x ffmpeg.7z -y
      # 3) Install dependencies (test + build)
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Run tests
      - name: Run tests
        run: |
          # Example: if you have pytest or unittest
          pytest --maxfail=1 --disable-warnings || exit 1

      # 5) Build EXE with PyInstaller
      - name: Build EXE
        run: |
          # e.g. "youtube_to_mp3.py" is your main script
          pyinstaller --onefile  --hide-console=hide-early --add-binary "ffmpeg.exe;."   --add-data "loading.gif;." --add-data "overlay.gif;." --icon=favicon.ico  youtube_to_mp3.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: youtube_to_mp3_exe
          path: dist/youtube_to_mp3.exe
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.run_number }}
          name: "Release ${{ github.run_number }}"
          body: "Auto-generated release for ${{ github.run_number }}"
          draft: false
          prerelease: false
          artifacts: "dist/youtube_to_mp3.exe"
